controller_manager:
    ros__parameters:
        update_rate: 100 # Hz

        joint_state_controller:
            type: position_controllers/JointGroupPositionController


joint_state_controller:
    ros__parameters:
        # List of joint names to be controlled by this controller
        joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5

        command_interface: position
