controller_manager:
    ros__parameters:
        update_rate: 100  # Hz

        effort_controllers:
            type: effort_controllers/JointGroupEffortController

        joint_state_controller:
            type: joint_state_broadcaster/JointStateBroadcaster

effort_controllers:
    ros__parameters:
        joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
        command_interfaces:
        - effort
        state_interfaces:
        - position
        - velocity
        - effort