controller_manager:
    ros__parameters:
        joint_trajectory_controller:
            type: joint_trajectory_controller/JointTrajectoryController

        joint_state_controller:
            type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
    ros__parameters:
        joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
        command_interfaces:
        - position
        state_interfaces:
        - position
        - velocity

        state_publish_rate: 200.0 # Defaults to 50
        action_monitor_rate: 20.0 # Defaults to 20

        allow_partial_joints_goal: false # Defaults to false
        open_loop_control: true
        allow_integration_in_goal_trajectories: true
        constraints:
            stopped_velocity_tolerance: 0.01 # Defaults to 0.01
            goal_time: 0.0 # Defaults to 0.0 (start immediately)
        gains.joint_1.p: 100.0
        gains.joint_1.i: 0.0
        gains.joint_1.d: 0.0
        gains.joint_2.p: 100.0
        gains.joint_2.i: 0.0
        gains.joint_2.d: 0.0
        gains.joint_3.p: 100.0
        gains.joint_3.i: 0.0
        gains.joint_3.d: 0.0
        gains.joint_4.p: 100.0
        gains.joint_4.i: 0.0
        gains.joint_4.d: 0.0
        gains.joint_5.p: 100.0
        gains.joint_5.i: 0.0
        gains.joint_5.d: 0.0